#! /bin/bash
###
# k-based virtual machines
# NABUCODONOSOR SERVER
# SCESI RULES!
# Part of the sassers system S-SYSTEM
###


echo "Setting up smith ..."

kvm -name smith -net nic,macaddr=1e:b6:86:69:4e:7a -net tap,ifname=tap2,script=no,downscript=no -net nic,vlan=1,macaddr=2e:d2:8a:d1:23:04 -net tap,vlan=1,ifname=tap3,script=no,downscript=no -hda /dev/vg-raid1/smith -hdb /dev/vg-raid1/smith-data -smp 2 -m 1G -nographic -boot c &

echo done
